name: Feature request
description: Suggest an idea for the game
title: "Feature: "
labels: [Suggestion]
body:
  - type: input
    id: categorie
    attributes:
      label: Feature type
      description: |
        Indicates the type of feature (gameplay, level design, story, performance...).
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe your feature request or suggestion in detail
      description: |
        A clear and concise description of what you want to happen.
    validations:
      required: true
